### ISSUE TITLE
部署到linux上，保存的时候提示系统错误暂无法处理

### ISSUE THREAD

**Issue by zzw6776** [maicong/qiugouda-love#1]
怎么解决呢

**Comment by maicong** [comment]
请给个截图

**Comment by zzw6776** [comment]
http://love.mrzzw.tk/

直接给你地址吧

**Comment by zzw6776** [comment]
不会php...都不知道去哪看错误日志...........

**Comment by maicong** [comment]
目录没有写权限： [love.php#L45](https://github.com/maicong/qiugouda-love/blob/master/love.php#L45)，你把年份的目录给个写入和读取的权限（今天是2016，后天就变2017了）

**Comment by zzw6776** [comment]
已解决 谢谢！

**Comment by zzw6776** [comment]
http://love.mrzzw.tk/love/2016/1483084828.html


这个404是我nginx没配置好吗

**Comment by maicong** [comment]
你看下2016目录下面是否存在1483084828.html文件

**Comment by zzw6776** [comment]
存在的  我估计是nginx转发没配置好  你能给我一份你的配置代码吗  谢谢

**Comment by maicong** [comment]
我的 Nginx 配置很复杂的
