### ISSUE TITLE
大佬，为啥那个love.js文件有错误

### ISSUE THREAD

**Issue by 2822162791** [maicong/qiugouda-love#2]

**Comment by maicong** [comment]
什么错误？

**Comment by 2822162791** [comment]
谢谢回复。原网页被翻译过了，符号有错，现在解决了。
请问怎么在
`<a href="index3.html" id="accept" src="resp.php?mess=表白成功了">如果你接受我，请点击这里 </a>`
里面添加链接，就是点击之后再跳转其他的网站

**Comment by maicong** [comment]
没听懂
